name: Deploy

on:
    schedule:
        - cron: "0 6 * * 1"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
              with:
                repository: WordPress/gutenberg
                
            -   uses: actions/setup-node@v1
                with:
                    node-version: '12.x'

            -   run: sudo apt-get install rsync
            
            # Post a message in slack
            - run: |
                curl -X POST -H 'Content-type: application/json' --data '{"text":"http:\/\/gutenberg-components.w3.style/ -- deployment started!"}' https://hooks.slack.com/services/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
                
            # Install JS dependencies
            -   run: npm ci
            
            # Build storybook
            -   run: npm run storybook:build

            # Add the server to known hosts
            -   run: |
                    mkdir -p ~/.ssh
                    touch ~/.ssh/known_hosts
                    ssh-keyscan -H w3.style >> ~/.ssh/known_hosts
                    
            # Add Private  key
            -   run: |
                    touch ~/.ssh/deploy_key
                    echo "${{secrets.DEPLOY_KEY}}" >> ~/.ssh/deploy_key
                    chmod 600 ~/.ssh/deploy_key
                    
            # Build(replace strings, etc.)
            -   name: Deploy
                run: rsync -avc -e 'ssh -i ~/.ssh/deploy_key' --delete ./storybook/build/ "${{secrets.SSH_USER_HOST}}":/opt/easyengine/sites/gutenberg-components.w3.style/app/htdocs
            
            # Post a message in slack
            - run: |
                curl -X POST -H 'Content-type: application/json' --data '{"text":"http:\/\/gutenberg-components.w3.style/ -- deployment finished!"}' https://hooks.slack.com/services/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
                
